ItemTypeToIdx = {
    'android.widget.TextView': 0,
    'android.widget.ImageView': 1,
    'android.widget.LinearLayout': 2,
    'android.widget.ImageButton': 3,
    'android.widget.Button': 4,
    'android.widget.CheckedTextView': 5,
    'android.widget.EditText': 6,
    'android.widget.Switch': 7,
    'android.view.View': 8,
    'android.widget.Image': 9,
    'android.webkit.WebView': 10,
    'android.widget.RelativeLayout': 11,
    'android.widget.CheckBox': 12,
    'android.widget.ToggleButton': 13,
    'android.widget.FrameLayout': 14,
    'android.widget.ListView': 15,
    'android.view.ViewGroup': 16,
    'android.widget.RadioButton': 17,
}

ActionToIdx = {
    'click': 0,
    'input': 1,
    'enter': 2,
    'response': 3,
    'swipe': 4,
    'back': 5,
    'clear': 6,
}
